#!/bin/bash
(
sudo /sbin/ifconfig ${1##/*0/} 192.168.1.1
# carnival, put your masks on and go
sudo /sbin/iptables -D POSTROUTING -t nat -s 192.168.1.0/24 ! -d 192.168.1.0/24 -j MASQUERADE >& /dev/null
sudo /sbin/iptables -t nat -s 192.168.1.0/24 ! -d 192.168.1.0/24 -A POSTROUTING -j MASQUERADE
#echo 1 > /proc/sys/net/ipv4/ip_forward
)>tunconfig.log 2>&1
